name: A Sétima Nébula
title: A Sétima Nébula 
description: A Sétima Nébula é um blog contendo artigos sobre temas relacionados à Engenharia de Dados, escritos de uma maneira simples e intuitiva.
tags:
  - blog
  - data
  - data engineering
  - code
  - programming
show_hero: true
menu:
  - title: Home
    url: /
  - title: Sobre
    url: /sobre
  - title: Contato
    url: /contato
  - title: Feed
    url: /feed.xml
#email: andre.luis.e3@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
#formspree_form_id: formspree_form_id
