name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev
        git clone https://github.com/rbenv/ruby-build.git $HOME/ruby-build
        cd $HOME/ruby-build
        sudo ./install.sh
        ruby-build 3.1.4 $HOME/.rubies/3.1.4
        echo 'export PATH="$HOME/.rubies/3.1.4/bin:$PATH"' >> $GITHUB_ENV
        echo 'export GEM_HOME=$HOME/.gem' >> $GITHUB_ENV
        echo 'export PATH=$GEM_HOME/bin:$PATH' >> $GITHUB_ENV

    - name: Install Bundler
      run: gem install bundler

    - name: Install Gems
      run: bundle install

    - name: Build Site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
